# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('flavor_text', models.CharField(blank=True, max_length=255, null=True)),
                ('in_deck', models.BooleanField(default=False)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardInDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deck.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('in_play', models.BooleanField(default=False)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('card_displayed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deck.Card')),
                ('cards', models.ManyToManyField(blank=True, help_text='Cards in the deck (Master list)', to='deck.CardInDeck')),
                ('cards_in_deck', models.ManyToManyField(blank=True, help_text='Cards in the deck', related_name='play_set', to='deck.Card')),
                ('cards_in_discard', models.ManyToManyField(blank=True, help_text='Cards in the discard pile', related_name='discard_set', to='deck.Card')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('open_draw', models.BooleanField(default=True, help_text='Allow anyone to draw a card')),
                ('secret', models.CharField(blank=True, help_text='Secret key to let someone in the room', max_length=50, null=True)),
                ('allow_guests', models.BooleanField(default=True, help_text='Allow anyone to play with the secret key without signing in')),
                ('finished', models.BooleanField(default=False, help_text='Mark for destruction')),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deck.Deck')),
                ('players', models.ManyToManyField(blank=True, help_text='Users allowed in game room', related_name='player_set', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
