# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='allow_guests',
            field=models.BooleanField(default=False, help_text='Allow anyone to play with the secret key without being signed into the website'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='secret',
            field=models.CharField(blank=True, help_text='Secret password to let someone in the room', max_length=50, null=True),
        ),
    ]
