# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='parent',
        ),
        migrations.AddField(
            model_name='card',
            name='in_deck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='finished',
            field=models.BooleanField(default=False, help_text='Mark for destruction'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck_played', to='deck.Deck'),
        ),
    ]
