# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_gameroom_allow_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='owner',
            new_name='user_created',
        ),
    ]
